"""
Smart Irrigation – Interactive Data Dashboard
==============================================
Run:  python irrigation_dashboard.py

Requires:
    pip install matplotlib pandas numpy

Expects these CSV files in the SAME folder (generated by generate_irrigation_data.py):
    irrigation_raw.csv
    irrigation_normalized.csv

Navigation:
    Use the sidebar buttons to switch between chart pages.
"""

import os
import sys
import warnings
warnings.filterwarnings("ignore")

import numpy as np
import pandas as pd
import matplotlib
import matplotlib.pyplot as plt
import matplotlib.gridspec as gridspec
import matplotlib.patches as mpatches
from matplotlib.backends.backend_tkagg import FigureCanvasTkAgg, NavigationToolbar2Tk
from matplotlib.figure import Figure
import tkinter as tk
from tkinter import ttk, messagebox

# ──────────────────────────────────────────────
#  THEME
# ──────────────────────────────────────────────
BG       = "#0f1117"
PANEL    = "#1a1d27"
ACCENT   = "#00c9a7"
ACCENT2  = "#7b61ff"
WARN     = "#ff6b6b"
YELLOW   = "#ffd166"
BLUE     = "#118ab2"
TEXT     = "#e8eaf6"
SUBTEXT  = "#8892a4"
GRID     = "#2a2d3a"

ANOMALY_COLORS = {
    "Normal":           "#00c9a7",
    "Night_Leak":       "#ff6b6b",
    "Pipe_Burst":       "#ff4500",
    "Over_Irrigation":  "#ffd166",
    "Under_Irrigation": "#7b61ff",
    "Rain_Event":       "#118ab2",
}

matplotlib.rcParams.update({
    "figure.facecolor":  BG,
    "axes.facecolor":    PANEL,
    "axes.edgecolor":    GRID,
    "axes.labelcolor":   TEXT,
    "axes.titlecolor":   TEXT,
    "xtick.color":       SUBTEXT,
    "ytick.color":       SUBTEXT,
    "text.color":        TEXT,
    "grid.color":        GRID,
    "grid.linewidth":    0.6,
    "legend.facecolor":  PANEL,
    "legend.edgecolor":  GRID,
    "legend.labelcolor": TEXT,
    "font.family":       "DejaVu Sans",
    "font.size":         9,
})

# ──────────────────────────────────────────────
#  DATA LOADING
# ──────────────────────────────────────────────
SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))

def load_data():
    raw_path  = os.path.join(SCRIPT_DIR, "irrigation_raw.csv")
    norm_path = os.path.join(SCRIPT_DIR, "irrigation_normalized.csv")
    missing = [p for p in [raw_path, norm_path] if not os.path.exists(p)]
    if missing:
        messagebox.showerror(
            "Missing Files",
            "Could not find:\n" + "\n".join(missing) +
            "\n\nRun  generate_irrigation_data.py  first."
        )
        sys.exit(1)

    raw  = pd.read_csv(raw_path,  parse_dates=["timestamp"], index_col="timestamp")
    norm = pd.read_csv(norm_path, parse_dates=["timestamp"], index_col="timestamp")
    return raw, norm

# ──────────────────────────────────────────────
#  CHART BUILDERS
# ──────────────────────────────────────────────

def style_ax(ax, title="", xlabel="", ylabel="", grid=True):
    ax.set_title(title, fontsize=11, fontweight="bold", pad=8, color=TEXT)
    ax.set_xlabel(xlabel, fontsize=8, color=SUBTEXT)
    ax.set_ylabel(ylabel, fontsize=8, color=SUBTEXT)
    if grid:
        ax.grid(True, alpha=0.4, linestyle="--")
    ax.spines[["top", "right"]].set_visible(False)
    ax.spines[["left", "bottom"]].set_color(GRID)


# PAGE 1 – Overview: one full day of raw sensor readings
def build_overview(df):
    fig = Figure(figsize=(14, 9), facecolor=BG, tight_layout=True)
    fig.suptitle("📊  Sensor Overview — First 7 Days", fontsize=14,
                 fontweight="bold", color=TEXT, y=0.98)

    sample = df.iloc[: 7 * 288]   # 7 days × 288 readings/day
    ts = sample.index

    sensors = [
        ("flow_lpm",          "Flow Rate (L/min)",     ACCENT,  "💧 Water Flow"),
        ("pressure_bar",      "Pressure (bar)",         BLUE,    "🔧 Pipeline Pressure"),
        ("soil_moisture_pct", "Soil Moisture (%)",      YELLOW,  "🌱 Soil Moisture"),
        ("temperature_c",     "Temperature (°C)",       WARN,    "🌡  Ambient Temperature"),
        ("rain_probability",  "Rain Probability",       ACCENT2, "🌧  Rain Forecast"),
    ]

    gs = gridspec.GridSpec(5, 1, figure=fig, hspace=0.55,
                           top=0.94, bottom=0.05, left=0.07, right=0.97)

    for i, (col, ylabel, color, title) in enumerate(sensors):
        ax = fig.add_subplot(gs[i])
        ax.fill_between(ts, sample[col], alpha=0.18, color=color)
        ax.plot(ts, sample[col], color=color, linewidth=0.9, label=ylabel)

        # shade irrigation windows
        irr = sample["is_irrigating"].values
        prev = 0
        for j, v in enumerate(irr):
            if v == 1 and prev == 0:
                start_ts = ts[j]
            if v == 0 and prev == 1:
                ax.axvspan(start_ts, ts[j], alpha=0.07, color=ACCENT, zorder=0)
            prev = v

        style_ax(ax, title=title, ylabel=ylabel)
        ax.tick_params(axis="x", labelsize=7)
        ax.tick_params(axis="y", labelsize=7)

    return fig


# PAGE 2 – Anomaly Timeline
def build_anomaly_timeline(df):
    fig = Figure(figsize=(14, 9), facecolor=BG, tight_layout=True)
    fig.suptitle("🚨  Anomaly Detection Timeline", fontsize=14,
                 fontweight="bold", color=TEXT, y=0.98)

    gs = gridspec.GridSpec(3, 1, figure=fig, hspace=0.55,
                           top=0.93, bottom=0.07, left=0.07, right=0.97)

    ax_flow = fig.add_subplot(gs[0])
    ax_pres = fig.add_subplot(gs[1])
    ax_label = fig.add_subplot(gs[2])

    # Downsample to keep rendering fast (every 3rd point)
    ds = df.iloc[::3]
    ts = ds.index

    # Flow
    ax_flow.plot(ts, ds["flow_lpm"], color=SUBTEXT, linewidth=0.5, alpha=0.6, zorder=1)
    for atype, color in ANOMALY_COLORS.items():
        if atype == "Normal":
            continue
        mask = ds["anomaly_type"] == atype
        if mask.any():
            ax_flow.scatter(ts[mask], ds["flow_lpm"][mask],
                            color=color, s=8, zorder=2, label=atype, alpha=0.85)
    style_ax(ax_flow, title="💧 Flow Rate with Anomalies", ylabel="L/min")
    ax_flow.legend(fontsize=7, ncol=3, loc="upper right",
                   framealpha=0.3, markerscale=2)

    # Pressure
    ax_pres.plot(ts, ds["pressure_bar"], color=SUBTEXT, linewidth=0.5, alpha=0.6, zorder=1)
    for atype, color in ANOMALY_COLORS.items():
        if atype == "Normal":
            continue
        mask = ds["anomaly_type"] == atype
        if mask.any():
            ax_pres.scatter(ts[mask], ds["pressure_bar"][mask],
                            color=color, s=8, zorder=2, alpha=0.85)
    style_ax(ax_pres, title="🔧 Pressure with Anomalies", ylabel="bar")

    # Anomaly label strip
    label_map_num = {
        "Normal": 0, "Night_Leak": 1, "Pipe_Burst": 2,
        "Over_Irrigation": 3, "Under_Irrigation": 4, "Rain_Event": 5
    }
    numeric = ds["anomaly_type"].map(label_map_num).fillna(0)
    for atype, color in ANOMALY_COLORS.items():
        if atype == "Normal":
            continue
        mask = ds["anomaly_type"] == atype
        if mask.any():
            ax_label.scatter(ts[mask], numeric[mask],
                             color=color, s=12, zorder=2, label=atype, alpha=0.9)

    ax_label.set_yticks(list(label_map_num.values()))
    ax_label.set_yticklabels(list(label_map_num.keys()), fontsize=7)
    style_ax(ax_label, title="🏷  Anomaly Label Strip", ylabel="")

    return fig


# PAGE 3 – Distribution & Statistics
def build_distributions(df):
    fig = Figure(figsize=(14, 9), facecolor=BG, tight_layout=True)
    fig.suptitle("📈  Sensor Distributions & Statistics", fontsize=14,
                 fontweight="bold", color=TEXT, y=0.98)

    gs = gridspec.GridSpec(2, 3, figure=fig, hspace=0.55, wspace=0.40,
                           top=0.93, bottom=0.07, left=0.07, right=0.97)

    sensor_cfg = [
        ("flow_lpm",          "Flow Rate (L/min)",   ACCENT),
        ("pressure_bar",      "Pressure (bar)",       BLUE),
        ("soil_moisture_pct", "Soil Moisture (%)",    YELLOW),
        ("temperature_c",     "Temperature (°C)",     WARN),
        ("rain_probability",  "Rain Probability",     ACCENT2),
    ]

    normal_df = df[df["anomaly_type"] == "Normal"]

    for i, (col, label, color) in enumerate(sensor_cfg):
        row, col_idx = divmod(i, 3)
        ax = fig.add_subplot(gs[row, col_idx])
        vals = normal_df[col].dropna()

        n_bins = 40
        counts, bins, patches = ax.hist(vals, bins=n_bins, color=color,
                                         alpha=0.75, edgecolor="none")
        ax.axvline(vals.mean(), color="white", linewidth=1.5,
                   linestyle="--", label=f"Mean: {vals.mean():.2f}")
        ax.axvline(vals.median(), color=YELLOW, linewidth=1.2,
                   linestyle=":", label=f"Median: {vals.median():.2f}")

        style_ax(ax, title=label, xlabel=label, ylabel="Count")
        ax.legend(fontsize=7, framealpha=0.3)

    # 6th panel – anomaly class balance (bar chart)
    ax6 = fig.add_subplot(gs[1, 2])
    counts = df["anomaly_type"].value_counts()
    bars = ax6.barh(counts.index, counts.values,
                    color=[ANOMALY_COLORS.get(t, SUBTEXT) for t in counts.index],
                    alpha=0.85, edgecolor="none", height=0.6)
    for bar, val in zip(bars, counts.values):
        ax6.text(val + 20, bar.get_y() + bar.get_height() / 2,
                 f"{val:,}", va="center", fontsize=7, color=TEXT)
    style_ax(ax6, title="🏷  Class Balance", xlabel="# Rows", grid=False)
    ax6.tick_params(axis="y", labelsize=7)

    return fig


# PAGE 4 – Correlation Heatmap + Scatter
def build_correlations(df):
    fig = Figure(figsize=(14, 9), facecolor=BG, tight_layout=True)
    fig.suptitle("🔗  Feature Correlations", fontsize=14,
                 fontweight="bold", color=TEXT, y=0.98)

    gs = gridspec.GridSpec(2, 2, figure=fig, hspace=0.50, wspace=0.35,
                           top=0.93, bottom=0.07, left=0.07, right=0.97)

    feature_cols = [
        "flow_lpm", "pressure_bar", "soil_moisture_pct",
        "temperature_c", "rain_probability",
        "flow_rolling_mean", "flow_rolling_std",
        "pressure_drop", "flow_deviation", "evap_index",
    ]
    corr = df[feature_cols].corr()

    # ── Heatmap (manual, no seaborn)
    ax_heat = fig.add_subplot(gs[0, :])
    im = ax_heat.imshow(corr.values, cmap="RdYlGn", vmin=-1, vmax=1, aspect="auto")
    fig.colorbar(im, ax=ax_heat, fraction=0.025, pad=0.02)
    ticks = range(len(feature_cols))
    ax_heat.set_xticks(ticks)
    ax_heat.set_yticks(ticks)
    ax_heat.set_xticklabels([c.replace("_", "\n") for c in feature_cols], fontsize=7)
    ax_heat.set_yticklabels(feature_cols, fontsize=7)
    for i in range(len(feature_cols)):
        for j in range(len(feature_cols)):
            val = corr.values[i, j]
            ax_heat.text(j, i, f"{val:.2f}", ha="center", va="center",
                         fontsize=6.5, color="black" if abs(val) > 0.5 else TEXT)
    ax_heat.set_title("Feature Correlation Matrix", fontsize=11,
                      fontweight="bold", color=TEXT, pad=8)

    # ── Scatter: Flow vs Pressure (coloured by anomaly type)
    ax_sc = fig.add_subplot(gs[1, 0])
    ds = df.sample(min(4000, len(df)), random_state=1)
    for atype, color in ANOMALY_COLORS.items():
        mask = ds["anomaly_type"] == atype
        if mask.any():
            ax_sc.scatter(ds["flow_lpm"][mask], ds["pressure_bar"][mask],
                          color=color, s=5, alpha=0.55, label=atype)
    style_ax(ax_sc, title="Flow vs Pressure", xlabel="Flow (L/min)", ylabel="Pressure (bar)")
    ax_sc.legend(fontsize=6.5, markerscale=2, framealpha=0.3, ncol=2)

    # ── Scatter: Soil Moisture vs Temperature
    ax_sc2 = fig.add_subplot(gs[1, 1])
    for atype, color in ANOMALY_COLORS.items():
        mask = ds["anomaly_type"] == atype
        if mask.any():
            ax_sc2.scatter(ds["temperature_c"][mask], ds["soil_moisture_pct"][mask],
                           color=color, s=5, alpha=0.55, label=atype)
    style_ax(ax_sc2, title="Temperature vs Soil Moisture",
             xlabel="Temperature (°C)", ylabel="Soil Moisture (%)")

    return fig


# PAGE 5 – Daily Patterns (hour-of-day aggregation)
def build_daily_patterns(df):
    fig = Figure(figsize=(14, 9), facecolor=BG, tight_layout=True)
    fig.suptitle("🕐  Daily Patterns (Hour-of-Day Averages)", fontsize=14,
                 fontweight="bold", color=TEXT, y=0.98)

    gs = gridspec.GridSpec(2, 3, figure=fig, hspace=0.55, wspace=0.40,
                           top=0.93, bottom=0.07, left=0.07, right=0.97)

    hours   = range(24)
    normal  = df[df["anomaly_type"] == "Normal"]
    hourly  = normal.groupby(normal.index.hour)

    sensors = [
        ("flow_lpm",          "Avg Flow (L/min)",     ACCENT),
        ("pressure_bar",      "Avg Pressure (bar)",   BLUE),
        ("soil_moisture_pct", "Soil Moisture (%)",    YELLOW),
        ("temperature_c",     "Temperature (°C)",     WARN),
        ("rain_probability",  "Rain Probability",     ACCENT2),
        ("evap_index",        "Evaporation Index",    "#f4a261"),
    ]

    for i, (col, ylabel, color) in enumerate(sensors):
        row, ci = divmod(i, 3)
        ax = fig.add_subplot(gs[row, ci])
        means  = hourly[col].mean()
        stds   = hourly[col].std()
        x      = means.index

        ax.fill_between(x, means - stds, means + stds, alpha=0.20, color=color)
        ax.plot(x, means, color=color, linewidth=2, marker="o", markersize=3)

        # mark irrigation windows
        ax.axvspan(6, 8,  alpha=0.08, color=ACCENT, zorder=0, label="Irrigation")
        ax.axvspan(17, 19, alpha=0.08, color=ACCENT, zorder=0)

        ax.set_xticks(range(0, 24, 3))
        ax.set_xticklabels([f"{h:02d}:00" for h in range(0, 24, 3)], fontsize=6.5)
        style_ax(ax, title=ylabel, xlabel="Hour of Day", ylabel=ylabel)

    return fig


# PAGE 6 – Normalized features (ML-ready view)
def build_normalized(df_norm):
    fig = Figure(figsize=(14, 9), facecolor=BG, tight_layout=True)
    fig.suptitle("⚙️  Normalized Features (ML-Ready, MinMax [0–1])", fontsize=14,
                 fontweight="bold", color=TEXT, y=0.98)

    feature_cols = [
        "flow_lpm", "pressure_bar", "soil_moisture_pct",
        "temperature_c", "rain_probability",
        "flow_rolling_mean", "flow_rolling_std", "pressure_drop",
        "flow_deviation", "evap_index",
    ]
    colors = [ACCENT, BLUE, YELLOW, WARN, ACCENT2,
              "#f4a261", "#e76f51", "#a8dadc", "#457b9d", "#2a9d8f"]

    gs = gridspec.GridSpec(2, 5, figure=fig, hspace=0.60, wspace=0.40,
                           top=0.93, bottom=0.07, left=0.06, right=0.97)

    normal  = df_norm[df_norm["anomaly_type"] == "Normal"]

    for i, (col, color) in enumerate(zip(feature_cols, colors)):
        row, ci = divmod(i, 5)
        ax = fig.add_subplot(gs[row, ci])
        vals = normal[col].dropna()
        ax.hist(vals, bins=35, color=color, alpha=0.80, edgecolor="none")
        ax.axvline(vals.mean(), color="white", linewidth=1.2, linestyle="--")
        label = col.replace("_", "\n")
        style_ax(ax, title=label, xlabel="Norm. Value", ylabel="Count")
        ax.tick_params(labelsize=7)
        mu, sd = vals.mean(), vals.std()
        ax.set_title(f"{label}\nμ={mu:.2f}  σ={sd:.2f}",
                     fontsize=8, color=TEXT, pad=4)

    return fig


# ──────────────────────────────────────────────
#  MAIN APPLICATION WINDOW
# ──────────────────────────────────────────────

class IrrigationDashboard(tk.Tk):
    def __init__(self, raw_df, norm_df):
        super().__init__()
        self.raw  = raw_df
        self.norm = norm_df
        self.title("💧  Smart Irrigation Data Dashboard")
        self.configure(bg=BG)
        self.geometry("1280x820")
        self.minsize(900, 600)

        self._pages = {}          # cache built figures
        self._current_canvas = None
        self._current_toolbar = None

        self._build_ui()
        self._show_page("Overview")

    # ── Layout ──────────────────────────────────
    def _build_ui(self):
        # ── Left sidebar
        sidebar = tk.Frame(self, bg=PANEL, width=180)
        sidebar.pack(side="left", fill="y")
        sidebar.pack_propagate(False)

        logo = tk.Label(sidebar, text="💧 IrriSense",
                        bg=PANEL, fg=ACCENT,
                        font=("DejaVu Sans", 13, "bold"), pady=18)
        logo.pack(fill="x")

        sep = tk.Frame(sidebar, bg=GRID, height=1)
        sep.pack(fill="x", padx=10, pady=4)

        pages = [
            ("📊  Overview",         "Overview"),
            ("🚨  Anomaly Timeline", "Anomaly Timeline"),
            ("📈  Distributions",    "Distributions"),
            ("🔗  Correlations",     "Correlations"),
            ("🕐  Daily Patterns",   "Daily Patterns"),
            ("⚙️   Normalized",       "Normalized"),
        ]

        self._btn_map = {}
        for label, key in pages:
            btn = tk.Button(
                sidebar, text=label, anchor="w",
                bg=PANEL, fg=TEXT,
                activebackground=ACCENT, activeforeground=BG,
                font=("DejaVu Sans", 9), padx=16, pady=10,
                bd=0, cursor="hand2", relief="flat",
                command=lambda k=key: self._show_page(k)
            )
            btn.pack(fill="x", padx=0, pady=1)
            self._btn_map[key] = btn

        # ── Info box at bottom of sidebar
        sep2 = tk.Frame(sidebar, bg=GRID, height=1)
        sep2.pack(fill="x", padx=10, pady=10, side="bottom")

        info = tk.Label(
            sidebar,
            text=f"Rows: {len(self.raw):,}\n"
                 f"Days: {(self.raw.index[-1]-self.raw.index[0]).days}\n"
                 f"Interval: 5 min\n"
                 f"Anomalies: {(self.raw['anomaly_type']!='Normal').sum():,}",
            bg=PANEL, fg=SUBTEXT, font=("DejaVu Sans", 8),
            justify="left", padx=14, pady=10
        )
        info.pack(fill="x", side="bottom")

        # ── Main content area
        self._content = tk.Frame(self, bg=BG)
        self._content.pack(side="right", fill="both", expand=True)

        # toolbar area
        self._toolbar_frame = tk.Frame(self._content, bg="#13161f", height=36)
        self._toolbar_frame.pack(fill="x", side="bottom")

        # canvas area
        self._canvas_frame = tk.Frame(self._content, bg=BG)
        self._canvas_frame.pack(fill="both", expand=True)

    def _show_page(self, key):
        # Highlight active button
        for k, btn in self._btn_map.items():
            btn.configure(bg=ACCENT if k == key else PANEL,
                          fg=BG   if k == key else TEXT)

        # Destroy previous canvas
        for w in self._canvas_frame.winfo_children():
            w.destroy()
        for w in self._toolbar_frame.winfo_children():
            w.destroy()

        # Build or retrieve cached figure
        if key not in self._pages:
            self.config(cursor="watch")
            self.update()
            builders = {
                "Overview":         lambda: build_overview(self.raw),
                "Anomaly Timeline": lambda: build_anomaly_timeline(self.raw),
                "Distributions":    lambda: build_distributions(self.raw),
                "Correlations":     lambda: build_correlations(self.raw),
                "Daily Patterns":   lambda: build_daily_patterns(self.raw),
                "Normalized":       lambda: build_normalized(self.norm),
            }
            self._pages[key] = builders[key]()
            self.config(cursor="")

        fig = self._pages[key]

        canvas = FigureCanvasTkAgg(fig, master=self._canvas_frame)
        canvas.draw()
        canvas.get_tk_widget().pack(fill="both", expand=True)

        toolbar = NavigationToolbar2Tk(canvas, self._toolbar_frame)
        toolbar.configure(bg="#13161f")
        toolbar.update()


# ──────────────────────────────────────────────
#  ENTRY POINT
# ──────────────────────────────────────────────
if __name__ == "__main__":
    print("Loading data...")
    try:
        raw_df, norm_df = load_data()
    except SystemExit:
        sys.exit(0)

    print(f"  ✓ {len(raw_df):,} rows loaded")
    print("Launching dashboard...")

    app = IrrigationDashboard(raw_df, norm_df)
    app.mainloop()